### ISSUE TITLE
Taro接入Zoro无法初始化redux state

### ISSUE THREAD

**Issue by zyktrcn** [FaureWu/zoro#41]
按照[接入taro](https://faurewu.github.io/zoro/GUIDE/TARO.html)教程搭建一个demo，
组件中无法正常显示redux中的state，
需要dispatch触发才能正常显示。
Taro版本 2.0.4
![image](https://user-images.githubusercontent.com/15548843/75006116-9ee26780-54ab-11ea-8ea9-9f471cd86fea.png)

**Comment by FaureWu** [comment]
@zyktrcn 可否提供代码

**Comment by zyktrcn** [comment]
`
//pages/index
import { connect } from '@tarojs/redux'
import { dispatcher } from '@opcjs/zoro' 
import './index.scss'

@connect(({ counter }) => ({
  counter
}))

class Index extends Component {

  constructor () {
    super()
  }

  componentWillMount () { 
    // this.handlerShow()
  }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { 
    console.log(this.props)
  }

  componentDidHide () { }

  config = {
    navigationBarTitleText: '首页'
  }

  handlerShow = () => dispatcher.counter.show()
  handlerAdd = () => {
    dispatcher.counter.add()
    console.log(this.props)
  }

  render () {

    const { counter } = this.props

    return (
      <View className='index'>
        <Text>{counter.num}</Text>
        <Button onClick={this.handlerAdd}>add</Button>
      </View>
    )
  }
}

export default Index

// app.js
import zoro from '@opcjs/zoro'
import counter from './models/counter'

import Index from './pages/index'

import './app.scss'

const app = zoro()
app.model(counter)
const store = app.start(false)

class App extends Component {

  componentDidMount () {
    app.setup()
  }

  componentDidShow () {}

  componentDidHide () {}

  componentDidCatchError () {}

  config = {
    pages: [
      'pages/index/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
}

Taro.render(<App />, document.getElementById('app'))

//models/counter
export default {
    namespace: 'counter',
    state: {
        num: 0
    },
    effects: {

    },
    reducers: {
        show (action, state) {
            return {
                ...state
            }
        },
        add (action, state) {
            return {
                ...state,
                num: state.num + 1
            }
        }
    }
}
`

**Comment by zyktrcn** [comment]
[https://github.com/zyktrcn/card-poj-cq-mp](demo)

**Comment by zyktrcn** [comment]
已解决
应该是constructor 中super继承导致props被覆盖？
